# Generated by Django 5.1.6 on 2025-03-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_order_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('pay_amount', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('quntity', models.CharField(blank=True, max_length=6, null=True)),
                ('pay_status', models.BooleanField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p_order',
            },
        ),
        migrations.AddField(
            model_name='nav_bar',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nav_bar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nav_bar/'),
        ),
    ]
