# Generated by Django 5.1.6 on 2025-04-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_order',
            name='check_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
