# Generated by Django 5.1.6 on 2025-03-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_p_order_nav_bar_display_nav_bar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav_bar',
            name='display',
        ),
        migrations.RemoveField(
            model_name='nav_bar',
            name='image',
        ),
    ]
