# Generated by Django 5.1.6 on 2025-03-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_nav_bar_display_remove_nav_bar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_bar',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nav_bar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nav_bar/'),
        ),
        migrations.AlterField(
            model_name='nav_bar',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
