# Generated by Django 5.1.6 on 2025-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_name_alter_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='transaction_id',
            field=models.CharField(max_length=255),
        ),
    ]
