# Generated by Django 5.1.6 on 2025-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_payment_details_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
