from django.urls import path
from .views import *
from .admin_views import *
urlpatterns = [
    path('',index,name="index"),
    path("contact/",contact,name="contact"),
    path("register/",register,name="register"),
    path("update_user/",update_user,name="update_user"),
    path("login/",admin_login,name="login"),
    path("verify/",verify_login,name="verify"),
    path('logout/',custom_logout, name='logout'),
    path('terms-of-use/', terms_of_use, name='terms_of_use'),
    path('refund-policy/', refund_policy, name='refund_policy'),
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    path('faqs/', faqs, name='faqs'),
    path('aboutus/', aboutus, name='aboutus'),
    path("shop/<int:id>/",shop,name="shop"),
    path("checkout/",checkout,name="checkout"),
    path("billing/",billing,name="billing"),
    path('products/', product_list_all, name='product_list_all'),
    path("category_products/<int:id>/",category_products,name="category_products"),
    path('search/', search_product, name='search_products'),
    path("user_orders_list/",user_orders_list,name="user_orders_list"),
    # path('create-payment/', create_payment, name='create_payment'),
    path('payment-success/<str:order>/<str:mobile>/<str:amount>/', payment_success, name='payment_success'),
    path('payment-webhook/', payment_webhook, name='payment_webhook'),
    path('update-order-status/', update_order_status, name='update_order_status'),

    # admin
    path('admin/dashboard/',admin_dashboard,name="admin"),
    path("add_category/",add_category,name="add_category"),
    path("category_list/",category_list,name="category_list"),
    path("category/<int:id>/", update_category, name="update_category"),
    path("add_sub_category/",add_sub_category,name="add_sub_category"),
    path("sub_category_list/",sub_category_list,name="sub_category_list"),
    path("sub_category/<int:id>/", update_subcategory, name="update_sub_category"),
    path("get_subcategories/",get_subcategories,name="get_subcategories"),
    path("add_product/",add_product,name="add_product"),
    path("add_product_list/",product_list,name="product_list"),
    path("update_product/<int:id>",update_product,name="update_product"),
    path("order_list/",order_list,name="order_list"),
    path("update_order/<int:id>/",update_order,name="update_order"),
    path('download-orders/<str:format>/', download_orders, name='download_orders'),
    path("update_check_status/",update_check_status,name="update_check_status"),
    path("update_check_p_order_status/",update_check_p_order_status,name="update_check_p_order_status"),
    path('p_order/',p_order,name="p_order"),
    path("p_order_list/",p_order_list,name="p_order_list"),
    path('upload-orders/', upload_orders, name='upload_orders'),
    path("track/<int:id>/",track_order,name="track_order"),
    path("track_p_order/<int:id>/",track_p_order,name="track_p_order"),

    path('update_nav_bar/', update_nav_bar, name='update_nav_bar'),
    path("nav_items/",nav_items,name="nav_items"),
    path("add_nav_item/",add_nav_item,name="add_nav_item"),
    path("navbar_headings/",navbar_headings,name="navbar_headings"),
    path("save_display_nav_items/",save_display_nav_items,name="save_display_nav_items"),
    path('save_display_category/', save_display_category, name='save_display_category'),
    path('remove-category/<int:id>/', remove_category, name='remove_category'),
    path('remove-sub-category/<int:id>/', remove_sub_category, name='remove_sub_category'),
    path('remove-product/<int:id>/', remove_product, name='remove_product'),
]
